import os
import re
import certifi
import airportsdata
import pycountry
from dotenv import load_dotenv

load_dotenv()


os.environ["SSL_CERT_FILE"] = certifi.where()
os.environ["REQUESTS_CA_BUNDLE"] = certifi.where()

API_KEY = os.getenv("AVIATIONSTACK_API_KEY")

# Default origin when user says only destination, e.g., "Flights to Paris"
# Change this if your default location is not Cairo, Egypt.
DEFAULT_ORIGIN_IATA = os.getenv("DEFAULT_ORIGIN_IATA", "CAI")

BASE_URL = "http://api.aviationstack.com/v1/flights"

AIRPORTS = airportsdata.load("IATA")  # Load IATA airport data

COUNTRY_ALIASES = {
    "usa": "US",
    "u.s.a": "US",
    "u.s.": "US",
    "america": "US",
    "united states": "US",
    "uk": "GB",
    "u.k.": "GB",
    "britain": "GB",
    "england": "GB",
    "uae": "AE",
    "dubai": "AE",
    "south korea": "KR",
    "korea": "KR",
    "russia": "RU",
    "vietnam": "VN",
    "bangladesh": "BD",
    "india": "IN",
    "japan": "JP",
    "china": "CN",
    "singapore": "SG",
    "malaysia": "MY",
    "thailand": "TH",
    "indonesia": "ID",
    "nepal": "NP",
    "qatar": "QA",
    "saudi arabia": "SA",
    "turkey": "TR",
    "canada": "CA",
    "australia": "AU",
    "germany": "DE",
    "france": "FR",
    "italy": "IT",
    "spain": "ES",
    "egypt": "EG",
    "cairo": "EG",
    "alexandria": "EG",
    "morocco": "MA",
    "casablanca": "MA",
    "tunisia": "TN",
    "algeria": "DZ",
    "kuwait": "KW",
    "oman": "OM",
    "bahrain": "BH",
    "jordan": "JO",
    "lebanon": "LB",
}


# Perferred main airport for country-level search
# Common airports for each country (IATA codes)
COUNTRY_MAIN_AIRPORTS = {
    "EG": ["CAI", "HBE", "SSH", "HRG"],
    "SA": ["JED", "RUH", "DMM", "MED"],
    "AE": ["DXB", "AUH", "SHJ"],
    "QA": ["DOH"],
    "KW": ["KWI"],
    "BH": ["BAH"],
    "OM": ["MCT"],
    "JO": ["AMM"],
    "LB": ["BEY"],
    "IQ": ["BGW", "EBL"],
    "MA": ["CMN", "RAK"],
    "DZ": ["ALG"],
    "TN": ["TUN"],
    "LY": ["TIP"],
    "BD": ["DAC"],
    "IN": ["DEL", "BOM", "BLR", "MAA"],
    "PK": ["ISB", "KHI", "LHE"],
    "NP": ["KTM"],
    "LK": ["CMB"],
    "CN": ["PEK", "PVG", "CAN"],
    "JP": ["HND", "NRT", "KIX"],
    "KR": ["ICN", "GMP"],
    "SG": ["SIN"],
    "MY": ["KUL"],
    "TH": ["BKK", "DMK", "HKT"],
    "VN": ["SGN", "HAN"],
    "ID": ["CGK", "DPS"],
    "PH": ["MNL"],
    "GB": ["LHR", "LGW", "MAN"],
    "FR": ["CDG", "ORY"],
    "DE": ["FRA", "MUC"],
    "IT": ["FCO", "MXP"],
    "ES": ["MAD", "BCN"],
    "NL": ["AMS"],
    "BE": ["BRU"],
    "CH": ["ZRH", "GVA"],
    "AT": ["VIE"],
    "PT": ["LIS"],
    "GR": ["ATH"],
    "IE": ["DUB"],
    "PL": ["WAW"],
    "CZ": ["PRG"],
    "HU": ["BUD"],
    "RO": ["OTP"],
    "SE": ["ARN"],
    "NO": ["OSL"],
    "DK": ["CPH"],
    "FI": ["HEL"],
    "US": ["JFK", "LAX", "ORD", "SFO", "MIA"],
    "CA": ["YYZ", "YVR", "YUL"],
    "MX": ["MEX"],
    "BR": ["GRU", "GIG"],
    "AR": ["EZE"],
    "CL": ["SCL"],
    "AU": ["SYD", "MEL", "BNE"],
    "NZ": ["AKL"],
    "ZA": ["JNB", "CPT"],
    "KE": ["NBO"],
    "ET": ["ADD"],
    "NG": ["LOS"],
}

CITY_MAIN_AIRPORT = {
    "cairo": "CAI",
    "alexandria": "HBE",
    "sharm el sheikh": "SSH",
    "hurghada": "HRG",
    "dhaka": "DAC",
    "delhi": "DEL",
    "new delhi": "DEL",
    "mumbai": "BOM",
    "kolkata": "CCU",
    "chennai": "MAA",
    "bangalore": "BLR",
    "bengaluru": "BLR",
    "islamabad": "ISB",
    "karachi": "KHI",
    "lahore": "LHE",
    "kathmandu": "KTM",
    "colombo": "CMB",
    "beijing": "PEK",
    "shanghai": "PVG",
    "guangzhou": "CAN",
    "tokyo": "HND",
    "narita": "NRT",
    "osaka": "KIX",
    "kyoto": "KIX",
    "seoul": "ICN",
    "singapore": "SIN",
    "kuala lumpur": "KUL",
    "bangkok": "BKK",
    "phuket": "HKT",
    "ho chi minh city": "SGN",
    "hanoi": "HAN",
    "jakarta": "CGK",
    "bali": "DPS",
    "manila": "MNL",
    "riyadh": "RUH",
    "jeddah": "JED",
    "medina": "MED",
    "dammam": "DMM",
    "dubai": "DXB",
    "abu dhabi": "AUH",
    "sharjah": "SHJ",
    "doha": "DOH",
    "kuwait city": "KWI",
    "manama": "BAH",
    "muscat": "MCT",
    "amman": "AMM",
    "beirut": "BEY",
    "baghdad": "BGW",
    "erbil": "EBL",
    "istanbul": "IST",
    "casablanca": "CMN",
    "marrakech": "RAK",
    "algiers": "ALG",
    "tunis": "TUN",
    "tripoli": "TIP",
    "london": "LHR",
    "manchester": "MAN",
    "paris": "CDG",
    "frankfurt": "FRA",
    "munich": "MUC",
    "rome": "FCO",
    "milan": "MXP",
    "madrid": "MAD",
    "barcelona": "BCN",
    "amsterdam": "AMS",
    "brussels": "BRU",
    "zurich": "ZRH",
    "geneva": "GVA",
    "vienna": "VIE",
    "lisbon": "LIS",
    "athens": "ATH",
    "dublin": "DUB",
    "warsaw": "WAW",
    "prague": "PRG",
    "budapest": "BUD",
    "bucharest": "OTP",
    "stockholm": "ARN",
    "oslo": "OSL",
    "copenhagen": "CPH",
    "helsinki": "HEL",
    "new york": "JFK",
    "los angeles": "LAX",
    "chicago": "ORD",
    "san francisco": "SFO",
    "miami": "MIA",
    "toronto": "YYZ",
    "vancouver": "YVR",
    "montreal": "YUL",
    "mexico city": "MEX",
    "sao paulo": "GRU",
    "rio de janeiro": "GIG",
    "buenos aires": "EZE",
    "santiago": "SCL",
    "sydney": "SYD",
    "melbourne": "MEL",
    "brisbane": "BNE",
    "auckland": "AKL",
    "johannesburg": "JNB",
    "cape town": "CPT",
    "nairobi": "NBO",
    "addis ababa": "ADD",
    "lagos": "LOS",
    "nyc": "JFK",
    "new york city": "JFK",
    "la": "LAX",
    "st petersburg": "LED",
    "saint petersburg": "LED",
    "bombay": "BOM",
    "calcutta": "CCU",
}

def clean_text(text: str) -> str:
    text = text.lower().strip()
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text)  # Remove special characters
    text = re.sub(r"\s+", " ", text)  # Replace multiple spaces with a single space
    
    stop_words = [
        "flight", "flights", "ticket", "tickets", "trip", "travel",
        "plan", "complete", "days", "day", "including", "hotel",
        "hotels", "sightseeing", "under", "budget", "info", "information"
    ]
    
    words = [w for w in text.split() if w not in stop_words]
    
    return " ".join(words).strip()